### PR TITLE
Update for Shrine 3.0

### PR DESCRIPTION
**Pull request by janko**
In Shrine 2.x we've already stopped using the `#download` storage method (see https://github.com/shrinerb/shrine/pull/331 for the rationale). So we can remove it here. The google client should already be doing resumable downloads in the `#open` method as well, so we shouldn't be losing anything by switching to `#open`.

Shrine 3.0 now requires the `#open` method to accept optional keyword arguments. We add the `:rewindable` option to allow people to disable `Down::ChunkedIO`'s disk caching, which has become a convention across Shrine storages. We also forward any additional options `Google::Cloud::Storage::File#download`, to give people more control over downloading should they want it.

Lastly, we relax the `shrine` version constraint to allow Shrine 3.x. Shrine 3.0 isn't officially released yet, but we already have a beta that seems pretty stable, and we'll soon be releasing a RC, so it would be nice if people can already test with GCS.

### CODE REVIEW

**Comment by janko** [comment]
I also remembered the Shrine 3.0 requires `#open` to raise `Shrine::FileNotFound` on missing file. I'm not sure to how detect it properly, so I was hoping to get some help from you.

I initially wanted to still keep allowing Shrine 2.x, but the new `Shrine::FileNotFound` exception doesn't exist in 2.x, so I bumped the shrine version specifier to >= 3.x.

**Comment by renchap** [comment]
Thanks @janko!
I am currently on vacation, I will review this and test my app with Shrine 3 once I am back (after the 7th of october). Feel free to ping me if I forget :)

**Comment by steveclarke** [comment]
Any update on merging this request? I'm ready to upgrade to Shrine 3.0 and this is a blocker. Much appreciated!

**Comment by renchap** [comment]
Thanks @janko!
This will go in the 3.0.0 release of this gem, as this is a breaking change. I will publish it soon.

**Comment by renchap** [comment]
Woops sorry, I missed this and I was minutes away from releasing the new version. I will have a look then :)

**Comment by renchap** [comment]
I just opened #40 for this.

**Comment by renchap** [comment]
Shrine 3.0 compatibility has just been released in version 3.0.0 🎉

**Pull request merged**
