### PR TITLE
Add: credentials support if specified

### PR DESCRIPTION
**Pull request by BKSpurgeon**
Why this PR?

* Allows for the passing in in credentials, if required. Credentials can be a whole variety of objects. The user may specify what the user wants, as refered to in the API docs: https://googleapis.dev/ruby/google-cloud-storage/latest/Google/Cloud/Storage.html#new-class_method

* Please do ensure / check you're happy with this before merging.

I hope this helps.

regards

Ben

### CODE REVIEW

**Comment by BKSpurgeon** [comment]
Hi Renaud
 
Also out of curiosity, were you able to get asynchronous uploads directly to a google bucket working?

*(I'm having some trouble setting the correct CORS headers plus i'm getting a few errors etc. which is why i'm asking). chrs

**Comment by ianks** [comment]
Had a similar patch here, FWIW: https://github.com/renchap/shrine-google_cloud_storage/pull/35

**Comment by BKSpurgeon** [comment]
@ianks cheers I did see that patch.

out of curiosity, where you able to get direct uploads to a google bucket set up? if so would you have a minimal example handy somewhere?

**Comment by BKSpurgeon** [comment]
@ianks #35 - there was an issue with passing in the options?

**Comment by ianks** [comment]
> @ianks #35 - there was an issue with passing in the options?

Looks like there is. Happy to let this PR supercede mine 😀

As far as direct upload with GCS, yes we got it to work. Email me at ian AT tryadhawk DOT com and I'll send example.

**Comment by BKSpurgeon** [comment]
@ianks chrs - you can let that PR through - just patch it up: the reason i put this one in was because I saw it had gone stale.......

rgds
Ben

**Comment by ianks** [comment]
Ok, just fixed my PR. @BKSpurgeon you can close this if you want.

**Comment by renchap** [comment]
Thanks @BKSpurgeon for this PR. It is similar to #35 and I would prefer to merge this other one, so I am closing this one and will be merging #35 as soon as my few comments here are addressed.

**Comment by renchap** [comment]
> Hi Renaud
> 
> Also out of curiosity, were you able to get asynchronous uploads directly to a google bucket working?
> 
> *(I'm having some trouble setting the correct CORS headers plus i'm getting a few errors etc. which is why i'm asking). chrs

@BKSpurgeon about this, did you look at Shrine's documentation? https://shrinerb.com/docs/plugins/presign_endpoint can be used to get the needed headers on the request.

It is working fine on my app (with Shrine 2 and custom client-side code), can you please open a separate issue if you want more help on this? Thanks!

**Comment by BKSpurgeon** [comment]
> > Hi Renaud
> > Also out of curiosity, were you able to get asynchronous uploads directly to a google bucket working?
> > *(I'm having some trouble setting the correct CORS headers plus i'm getting a few errors etc. which is why i'm asking). chrs
> 
> @BKSpurgeon about this, did you look at Shrine's documentation? https://shrinerb.com/docs/plugins/presign_endpoint can be used to get the needed headers on the request.
> 
> It is working fine on my app (with Shrine 2 and custom client-side code), can you please open a separate issue if you want more help on this? Thanks!

Yes thanks Renaud I got the CORS working. 

The only issue I'm having is getting uppy to integrate well with google cloud. With amazon, all the fields are nicely handled in `file.meta`, but with Google cloud storage, the `file.meta` isn't returning the expected keys: this is an issue with uppy?

```javascript
 uppy.on('upload-success', (file, response) => {
    // construct uploaded file data in the format that Shrine expects
    const uploadedFileData = {
      id: file.meta['key'].match(/^cache\/(.+)/)[1], // <------------- file.meta is not behaving.
      storage: 'cache',
      metadata: {
        size: file.size,
        filename: file.name,
        mime_type: file.type,
      }
    }
```

**Comment by renchap** [comment]
I am not using Uppy but custom JS code, so I am not really sure whats happening here. What does `file` look like (add a `console.log(file)` at the top of your callback function to check)

**Pull request closed without merging**
