### PR TITLE
url method to return signed url by default

### PR DESCRIPTION
**Pull request by majksner**
Instead of passing expires when calling #{attribute}_url check for default_acl and generate signed url always, if default_acl is set to publicRead in initializer then public url will be printed.

### CODE REVIEW

**Comment by renchap** [comment]
Thanks @majksner for this PR.

I am not sure of what is the convention in other Shrine storages, forcing the user to add an `expires` option makes it explicit that you want a signed URL to a resource that would not be accessible otherwise and I worry a bit that it could lead people to inadvertently generate URLs to private objects without it being obvious.

@janko Do you have an opinion here?

**Comment by janko** [comment]
The official S3 Shrine storage accepts a `:public` option in the initializer, which makes uploads use the public-read ACL by default, and URLs to be public by default.

**Comment by vanboom** [comment]
My PR also works to improve the `url` method by encoding the filename.  This PR is almost 2 years old.  Can it be dispositioned please?  or rejected/closed?

**Comment by renchap** [comment]
As you can see by running the tests, this PR changes the default behavior and will require people to change their code to account for it, so it would require a major version bump of the gem.
I am still not convinced it is a good idea to generate signed URLs by default and I prefer to make it explicit when you want to generate signed URLs and make private objects publicly accessible.

Test run for this version:
```bundle exec rake test
Run options: --seed 52715

# Running:

.............FFF.........

Fabulous run in 33.553212s, 0.7451 runs/s, 1.6988 assertions/s.

  1) Failure:
Shrine::Storage::GoogleCloudStorage::#url#test_0002_encodes the filename in the URL [/Users/renchap/dev/shrine-google_cloud_storage/test/gcs_test.rb:295]:
--- expected
+++ actual
@@ -1 +1 @@
-"https://storage.googleapis.com/shrine-gcs-test-renchap-shrine-gcs-test2/1a1dbe5248174862fbe6e0069102bbf5%23test"
+"https://storage.googleapis.com/shrine-gcs-test-renchap-shrine-gcs-test2/1a1dbe5248174862fbe6e0069102bbf5#test?GoogleAccessId=shrine-gcs-test%40renchap-shrine-gcs-test2.iam.gserviceaccount.com&Expires=1641552381&Signature=lnnruK0JGUz2pK88qjzW6C%2BXGOr8xib66bBft5w322a0RBb5uMXu3eiddgTqRMQrXrTG1csQs%2B%2BYXXjAWGbJcukjMzYdPcMGdKcMImiQrrjjHf5tyKqEtUTPx%2Fea7vz4UPZzHpO23ukqkximMPTioGSo0nw0QhgC7QpDdpcr0qL2jCO%2F0mmZHSi%2FKylHXLUM%2B3fEIg7kmgjyXz%2BI0BuP0odSejckyMWqYQdFNyLHw2YHqaq1HOZ4BDp2oKljxfhkBHu6A%2BXmiYco9fXkQknqrI9h8JxCiPvREUbA23JLaUtF2dLgcYXHQbe1CSHdhw%2BmLh3%2BkkjZnVNFq%2B5uCV%2BWYQ%3D%3D"


  2) Failure:
Shrine::Storage::GoogleCloudStorage::#url#test_0003_accepts :host for specifying CDN links [/Users/renchap/dev/shrine-google_cloud_storage/test/gcs_test.rb:304]:
--- expected
+++ actual
@@ -1 +1 @@
-"https://123.mycdn.net/4d03eba985ab944446375c4cdbced248"
+"https://123.mycdn.net/4d03eba985ab944446375c4cdbced248?GoogleAccessId=shrine-gcs-test%40renchap-shrine-gcs-test2.iam.gserviceaccount.com&Expires=1641552381&Signature=U4rv6uBNm1lF11tKDCFlzX4yOVHYPwNyBqK7wLeGUZVqmmzeqJfQndLc2MFNJ1h54IwQJL37gypenQMlj5glsaBUKX29uFUPXKw90%2BetRWkXD%2Bl9n3goU3KdTE8v7c%2FJtAAxnnuIhR%2F5H5vsszIxgYNYS2rJ05t3gAGxLL%2FWNwOVf5WjXB8T3Zwm176V5JVvdFwSNktr%2BB7dKDtMcKzdUbH41EuFJuC2q4W0JOvTLqFrPA8HrMGmqaqqTFwgt1gbJaduZHLl%2Bas3YV4Pgnrj1LAweav2WWXeECXRiXyut3VUNmgS5qdh0iddetXNAMMB06pRQHQeSqjERRPLaMT35w%3D%3D"


  3) Failure:
Shrine::Storage::GoogleCloudStorage::#url#test_0001_provides a storage.googleapis.com url by default [/Users/renchap/dev/shrine-google_cloud_storage/test/gcs_test.rb:287]:
--- expected
+++ actual
@@ -1 +1 @@
-"https://storage.googleapis.com/shrine-gcs-test-renchap-shrine-gcs-test2/6480e4bf55c488034890c46b5e910a09"
+"https://storage.googleapis.com/shrine-gcs-test-renchap-shrine-gcs-test2/6480e4bf55c488034890c46b5e910a09?GoogleAccessId=shrine-gcs-test%40renchap-shrine-gcs-test2.iam.gserviceaccount.com&Expires=1641552381&Signature=CNLXGTBI9pZ%2FsCH3xl3TEBgIVuiP2Lk0v7gtxGcU1GhK0MgfMRk1G%2B2kgPHYCt5Gj484Tc9%2BTFHHIigGDHSI3DlRsSTgGz7i%2FXXeUmkJOGtVQoMvDk9yPSiANgDIPk1MrkJ7HpDaeSuQ8V9w9L%2BI768RuOtib1ROLcMNZBxPUQYEyC0277nuIoruECrzsWiigbTxKXePsJeXWUviqX8UMZZw6HvSVIKjhj69c0MnjhJKA3ReVSVDfQVhu1K%2B4NIX4McXr4l8utHWy4pEbrbZfSPXNDupFa55y%2BKq%2F7AuImlbY7AvtGrRCN3Apue8lq3KievM8vj9jdavnTYbSYvBVw%3D%3D"
```

**Pull request closed without merging**
