### PR TITLE
fix(dependency) : bumped google-cloud-storage dependency

### PR DESCRIPTION
**Pull request by valentinjadot**
"google-cloud-storage" dependency has been updated to version 1.21.1.

### CODE REVIEW

**Comment by quartzmo** [comment]
Great! Please let me know if this change causes any issues, thanks.

**Comment by valentinjadot** [comment]
Sorry I went too fast, will PR later when everything is ready

**Comment by waclock** [comment]
It'd be great if this PR could be merged!

**Comment by renchap** [comment]
These changes were included in #37. Also see discussion in #38

**Pull request closed without merging**
